In [3]:
import numpy as np

In [17]:
x = np.array([[2, 1]])
print(x.shape)
print(x.ndim)

(1, 2)
2


In [14]:
x = np.array([[1, 2, 3], [4, 5, 6], [-1, 3, 4]])
a = np.array([[4, 2, -3]])
print(x)
print(x.ndim)
print(x.shape)
print(a.ndim)
#print(a.shape)
print(np.concatenate((x, a.T), axis = 1))

[[ 1  2  3]
 [ 4  5  6]
 [-1  3  4]]
2
(3, 3)
2
[[ 1  2  3  4]
 [ 4  5  6  2]
 [-1  3  4 -3]]


In [7]:
a = np.array([4, 2, -3])
print(a.shape)

(3,)


In [ ]:
def reduction_matrix(a):
    