## Write a program to solve the following systems of linear equations using LU decomposition

In [2]:
import numpy as np 
C0 = np.array([[1, -2, 1], [2, 1, -3], [4, -7, 1]], dtype = float)
C1 = np.array([[1, 2, -1, 1], [-1, 1, 2, -1], [2, -1, 2, 2], [1, 1, -1, 2]], dtype = float)
x1 = np.array([6, 3, 14, 8], dtype = float)
x = np.array([0, 5, -1], dtype = float)

def LU_decomposition(A, B):
    n = len(B)
    L = np.zeros((n, n))
    for i in range(n-1):
        for j in range(i+1, n):
            fac = A[j,i]/A[i,i]
            L[j, i] = fac
            B[j] -= fac * B[i]
            A[j,i] = 0
            for k in range(i+1, n):
                A[j, k]-= fac * A[i, k]
    np.fill_diagonal(L, 1)
    y0 = np.zeros((n))
    y1 = np.zeros((n))
    
    for p in range(0, n):
        y0[p] = (B[p] - np.dot(L[p, p+1:], y0[p+1:]))/L[p, p]
          
    for q in range(n-1, -1, -1):
        y1[q] = (y0[q] - np.dot(A[q, q+1:], y1[q+1:]))/A[q, q]
 
    return y1

print(LU_decomposition(C0, x))

print(LU_decomposition(C1, x1))

[3. 2. 1.]
[1. 2. 3. 4.]


## Inverse of a matrix and computation of $X = A^{-1} Y$

In [6]:
def inverse_matrix(A):
    n = np.shape(A)[0]
    I = np.identity(n)
    Ainv = np.zeros((n, n))
    
    for k in range(n):
        Ainv[:, k] = LU_decomposition(A, I[:, k])
        
    return Ainv

print(inverse_matrix(C0) @ x)
print(inverse_matrix(C1) @ x1)

[3. 2. 1.]
[1. 2. 3. 4.]


## Familiarization with scipy routines: repeat (1) using scipy.linalg.lu_factor and scipy.linalg.lu_solve

In [7]:
from scipy.linalg import lu_factor, lu_solve

lu0, piv0 = lu_factor(C0)
x0 = lu_solve((lu0, piv0), x)
print(x0)
lu1, piv1 = lu_factor(C1)
x1 = lu_solve((lu1, piv1), x1)
print(x1)

[3. 2. 1.]
[1. 2. 3. 4.]
